

/**:
  ros__parameters:  # pour définir des variables pour tout le monde
    display_length_video: 800.0
    nb_ROV : 1.0 # nombre de rov en simultané


blinky:


  control_blinky: # Fait référence au nom du node executé
    ros__parameters: # Attention, il y a deux "_"
      ROV_name: 'blinky'
      ID: 1.0
      param: "parameters_blinky"
      nb_cam: 1.0
      nb_target_cam: 1.0
      ip_adress_light: "192.168.4"
      num_beacon: 1.0



  ihm_blinky : # Fait référence au nom du node executé
    ros__parameters: # Attention, il y a deux "_"
      ROV_name: 'blinky'
      ID: 1.0


  tracking_blinky: # Fait référence au nom du node executé
    ros__parameters: # Attention, il y a deux "_"
      ROV_name: 'blinky'
      ID: 1.0
      camera_port_udp: 5900.0
      affichage_on: 1.0 # 1.0 : affichage on / 0.0 : affichage off
      num_cam : 1.0

  affichage_blinky: # Fait référence au nom du node executé
    ros__parameters: # Attention, il y a deux "_"
      ROV_name: 'blinky'
      ID: 1.0


